import { useMemo, useState } from "react";
import { useQuery } from "@tanstack/react-query";
import { getBranchId } from "../../lib/store";
import { ReportLayout, DataTable, GOLD, SURF, BORD, MUTED, DIM, TEXT } from "./layout";
import type { ColDef } from "./layout";

type Filter = "today" | "yesterday" | "week" | "month" | "year" | "custom";
function range(filter: Filter, from: string, to: string): [Date, Date] { const n = new Date(); const day = (d: Date) => new Date(d.getFullYear(), d.getMonth(), d.getDate()); if (filter === "today") return [day(n), n]; if (filter === "yesterday") { const d = new Date(n); d.setDate(d.getDate() - 1); return [day(d), new Date(d.getFullYear(), d.getMonth(), d.getDate(), 23, 59, 59)]; } if (filter === "week") { const d = new Date(n); d.setDate(d.getDate() - 6); return [day(d), n]; } if (filter === "month") { const d = new Date(n); d.setDate(d.getDate() - 29); return [day(d), n]; } if (filter === "year") return [new Date(n.getFullYear(), 0, 1), n]; return [from ? new Date(from) : day(n), to ? new Date(`${to}T23:59:59`) : n]; }
const columns: ColDef[] = [{ key: "cashierName", label: "Cashier" }, { key: "orderType", label: "Order Type" }, { key: "orders", label: "Invoiced Orders", align: "right" }, { key: "cash", label: "Cash", align: "right", render: v => `LKR ${Number(v || 0).toLocaleString()}` }, { key: "card", label: "Card", align: "right", render: v => `LKR ${Number(v || 0).toLocaleString()}` }, { key: "other", label: "Other", align: "right", render: v => `LKR ${Number(v || 0).toLocaleString()}` }, { key: "totalSales", label: "Total Sales", align: "right", render: v => <span style={{ color: GOLD, fontWeight: 700 }}>LKR {Number(v || 0).toLocaleString()}</span> }];
export default function CashierSalesReport() { const branchId = getBranchId(); const [filter, setFilter] = useState<Filter>("today"); const [from, setFrom] = useState(""); const [to, setTo] = useState(""); const { data, isLoading } = useQuery({ queryKey: ["reporting-sales", branchId], queryFn: async () => (await fetch(`/api/reporting?branchId=${branchId}`)).json() }); const [start, end] = range(filter, from, to); const orderRows = useMemo(() => ((data?.orderRows || []) as any[]).filter(o => { const d = new Date(o.dateTime || 0); return d >= start && d <= end && o.saleStatus === "Converted to sale"; }), [data, start.getTime(), end.getTime()]); const rows = useMemo(() => { const map = new Map<string, any>(); for (const o of orderRows) { const k = `${o.cashierName}|${o.typeLabel}`; const r = map.get(k) || { cashierName: o.cashierName, orderType: o.typeLabel, orders: 0, cash: 0, card: 0, other: 0, totalSales: 0 }; r.orders++; r.totalSales += o.total; for (const p of o.payments || []) { const m = String(p.method).toLowerCase(); if (m.includes("cash")) r.cash += p.amount; else if (m.includes("card")) r.card += p.amount; else r.other += p.amount; } map.set(k, r); } return [...map.values()].map(r => Object.fromEntries(Object.entries(r).map(([k, v]) => [k, typeof v === "number" ? Number(v.toFixed(2)) : v]))); }, [orderRows]); const filters: [Filter, string][] = [["today", "Today"], ["yesterday", "Yesterday"], ["week", "This Week"], ["month", "This Month"], ["year", "This Year"], ["custom", "Custom"]]; const total = rows.reduce((s, r) => s + r.totalSales, 0); return <ReportLayout title="Cashier-wide Sales"><div className="flex flex-wrap gap-2 items-center justify-between"><div className="flex flex-wrap gap-2">{filters.map(([key, label]) => <button key={key} onClick={() => setFilter(key)} className="px-3 py-1.5 rounded-lg text-xs font-semibold border" style={{ background: filter === key ? GOLD : "transparent", color: filter === key ? "var(--color-surface)" : MUTED, borderColor: filter === key ? GOLD : BORD }}>{label}</button>)}{filter === "custom" && <><input type="date" value={from} onChange={e => setFrom(e.target.value)} /><input type="date" value={to} onChange={e => setTo(e.target.value)} /></>}</div><button onClick={() => window.print()} className="px-3 py-1.5 rounded-lg text-xs font-semibold border" style={{ borderColor: BORD, color: MUTED }}>Print / PDF</button></div><div className="rounded-xl border p-4" style={{ background: SURF, borderColor: BORD }}><div className="text-xl font-bold" style={{ color: GOLD }}>LKR {Math.round(total).toLocaleString()}</div><div className="text-xs" style={{ color: DIM }}>Finalized sales for selected period</div></div>{isLoading ? <div style={{ color: DIM }}>Loading…</div> : <DataTable title={`Cashier and order type summary (${rows.length})`} columns={columns} rows={rows} exportName="cashier-sales-report" />}</ReportLayout>; }

