import { useMemo, useState } from "react";
import { useQuery } from "@tanstack/react-query";
import { getBranchId } from "../../lib/store";
import { ReportLayout, DataTable, GOLD, SURF, BORD, MUTED, DIM, TEXT } from "./layout";
import type { ColDef } from "./layout";

type Preset = "today" | "yesterday" | "week" | "month" | "year" | "custom";
type Criteria = { from: string; to: string; user: string; printer: string; table: string; type: string; printStatus: string; invoiceStatus: string };
const emptyCriteria: Criteria = { from: "", to: "", user: "", printer: "", table: "", type: "", printStatus: "", invoiceStatus: "" };
function formatDateTime(value: unknown) { if (!value) return "—"; const d = new Date(String(value)); return Number.isNaN(d.getTime()) ? "—" : d.toLocaleString("en-GB", { day: "2-digit", month: "2-digit", year: "numeric", hour: "2-digit", minute: "2-digit", second: "2-digit", hour12: false }).replace(",", ""); }
function presetRange(preset: Preset, from: string, to: string): [Date, Date] { const now = new Date(); const day = (d: Date) => new Date(d.getFullYear(), d.getMonth(), d.getDate()); if (preset === "today") return [day(now), now]; if (preset === "yesterday") { const d = new Date(now); d.setDate(d.getDate() - 1); return [day(d), new Date(d.getFullYear(), d.getMonth(), d.getDate(), 23, 59, 59)]; } if (preset === "week") { const d = new Date(now); d.setDate(d.getDate() - 6); return [day(d), now]; } if (preset === "month") { const d = new Date(now); d.setDate(d.getDate() - 29); return [day(d), now]; } if (preset === "year") return [new Date(now.getFullYear(), 0, 1), now]; return [from ? new Date(`${from}T00:00:00`) : new Date(0), to ? new Date(`${to}T23:59:59`) : now]; }
function options(rows: any[], key: string) { return [...new Set(rows.map(r => String(r[key] || "")).filter(Boolean))].sort(); }
const filterLabel: Record<keyof Criteria, string> = { from: "From date", to: "To date", user: "Printed by", printer: "Counter / Printer", table: "Table", type: "Type", printStatus: "Print status", invoiceStatus: "Invoice status" };
const columns: ColDef[] = [
  { key: "kotNumber", label: "KOT #" }, { key: "orderNumber", label: "Order #" }, { key: "dateTime", label: "Date / Time", render: v => formatDateTime(v) },
  { key: "userName", label: "Printed By" }, { key: "printerName", label: "Counter / Printer" }, { key: "tableName", label: "Table" },
  { key: "orderType", label: "Type" }, { key: "printStatus", label: "Print Status" }, { key: "invoiceStatus", label: "Invoice Status" },
];
export default function KOTReport() {
  const branchId = getBranchId(); const [preset, setPreset] = useState<Preset>("today"); const [from, setFrom] = useState(""); const [to, setTo] = useState(""); const [filterOpen, setFilterOpen] = useState(false); const [criteria, setCriteria] = useState<Criteria>(emptyCriteria); const [draft, setDraft] = useState<Criteria>(emptyCriteria);
  const { data, isLoading } = useQuery({ queryKey: ["reporting-kot", branchId], queryFn: async () => (await fetch(`/api/reporting?branchId=${branchId}`)).json() });
  const allRows = (data?.kotRows || []) as any[]; const [start, end] = presetRange(preset, from, to);
  const rows = useMemo(() => allRows.filter(r => { const date = new Date(r.dateTime || 0); return date >= start && date <= end && (!criteria.from || date >= new Date(`${criteria.from}T00:00:00`)) && (!criteria.to || date <= new Date(`${criteria.to}T23:59:59`)) && (!criteria.user || r.userName === criteria.user) && (!criteria.printer || r.printerName === criteria.printer) && (!criteria.table || r.tableName === criteria.table) && (!criteria.type || r.orderType === criteria.type) && (!criteria.printStatus || r.printStatus === criteria.printStatus) && (!criteria.invoiceStatus || r.invoiceStatus === criteria.invoiceStatus); }), [allRows, start.getTime(), end.getTime(), criteria]);
  const converted = rows.filter(r => r.invoiceStatus === "Converted to invoice").length; const left = rows.filter(r => r.invoiceStatus === "Left / not invoiced").length; const presets: [Preset, string][] = [["today", "Today"], ["yesterday", "Yesterday"], ["week", "This Week"], ["month", "This Month"], ["year", "This Year"], ["custom", "Custom"]];
  const updateDraft = (key: keyof Criteria, value: string) => setDraft(prev => ({ ...prev, [key]: value }));
  const activeFilters = Object.values(criteria).filter(Boolean).length;
  return <ReportLayout title="KOT Report">
    <div className="flex flex-wrap gap-2 items-center justify-between"><div className="flex flex-wrap gap-2">{presets.map(([key, label]) => <button key={key} onClick={() => setPreset(key)} className="px-3 py-1.5 rounded-lg text-xs font-semibold border" style={{ background: preset === key ? GOLD : "transparent", color: preset === key ? "var(--color-surface)" : MUTED, borderColor: preset === key ? GOLD : BORD }}>{label}</button>)}{preset === "custom" && <><input type="date" value={from} onChange={e => setFrom(e.target.value)} /><input type="date" value={to} onChange={e => setTo(e.target.value)} /></>}</div><div className="flex gap-2"><button onClick={() => { setDraft(criteria); setFilterOpen(true); }} className="px-3 py-1.5 rounded-lg text-xs font-semibold border" style={{ borderColor: GOLD, color: GOLD }}>Filter{activeFilters ? ` (${activeFilters})` : ""}</button><button onClick={() => window.print()} className="px-3 py-1.5 rounded-lg text-xs font-semibold border" style={{ borderColor: BORD, color: MUTED }}>Print / PDF</button></div></div>
    <div className="grid grid-cols-3 gap-3">{[["Filtered KOT entries", rows.length], ["Converted to Invoice", converted], ["Left / Not Invoiced", left]].map(([label, value]) => <div key={String(label)} className="rounded-xl border p-4" style={{ background: SURF, borderColor: BORD }}><div className="text-xl font-bold" style={{ color: GOLD }}>{value}</div><div className="text-xs" style={{ color: DIM }}>{label}</div></div>)}</div>
    {isLoading ? <div className="text-sm" style={{ color: DIM }}>Loading…</div> : <DataTable title={`KOT results (${rows.length} entries)`} columns={columns} rows={rows} exportName="kot-report" />}
    {filterOpen && <div className="fixed inset-0 z-50 flex items-center justify-center bg-black/50 p-4"><div className="w-full max-w-2xl rounded-2xl border p-5" style={{ background: SURF, borderColor: BORD }}><div className="flex items-center justify-between mb-4"><h2 className="font-bold" style={{ color: TEXT }}>Filter KOT report</h2><button onClick={() => setFilterOpen(false)} style={{ color: MUTED }}>Close</button></div><div className="grid grid-cols-1 sm:grid-cols-2 gap-3">{(["from", "to"] as const).map(key => <label key={key} className="text-xs" style={{ color: MUTED }}>{filterLabel[key]}<input type="date" value={draft[key]} onChange={e => updateDraft(key, e.target.value)} className="mt-1 w-full rounded-lg border px-2 py-2" style={{ background: SURF, borderColor: BORD, color: TEXT }} /></label>)}{(["user", "printer", "table", "type", "printStatus", "invoiceStatus"] as const).map(key => <label key={key} className="text-xs" style={{ color: MUTED }}>{filterLabel[key]}<select value={draft[key]} onChange={e => updateDraft(key, e.target.value)} className="mt-1 w-full rounded-lg border px-2 py-2" style={{ background: SURF, borderColor: BORD, color: TEXT }}><option value="">All</option>{options(allRows, key === "user" ? "userName" : key === "printer" ? "printerName" : key === "table" ? "tableName" : key === "type" ? "orderType" : key === "printStatus" ? "printStatus" : "invoiceStatus").map(value => <option key={value} value={value}>{value}</option>)}</select></label>)}</div><div className="flex justify-end gap-2 mt-5"><button onClick={() => { setCriteria(emptyCriteria); setDraft(emptyCriteria); }} className="px-3 py-2 rounded-lg text-xs border" style={{ borderColor: BORD, color: MUTED }}>Clear</button><button onClick={() => { setCriteria(draft); setFilterOpen(false); }} className="px-4 py-2 rounded-lg text-xs font-semibold" style={{ background: GOLD, color: "var(--color-surface)" }}>Apply filters</button></div></div></div>}
  </ReportLayout>;
}
